name: Check

on:
  push:
    branches: [main]
    paths:
      - package.json
      - grammar.js
  pull_request:
    paths:
      - package.json
      - grammar.js

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{vars.NODE_VERSION}}
      - name: Install modules
        run: npm ci --legacy-peer-deps
      - name: Run lint
        run: npm run lint
      - name: Run check
        run: npm run check
